// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v4.23.3
// source: tasks.proto

package tasks

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	TaskService_CreateTask_FullMethodName  = "/tasks.TaskService/CreateTask"
	TaskService_GetTask_FullMethodName     = "/tasks.TaskService/GetTask"
	TaskService_ListTasks_FullMethodName   = "/tasks.TaskService/ListTasks"
	TaskService_RecordTasks_FullMethodName = "/tasks.TaskService/RecordTasks"
	TaskService_TaskChat_FullMethodName    = "/tasks.TaskService/TaskChat"
)

// TaskServiceClient is the client API for TaskService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TaskServiceClient interface {
	CreateTask(ctx context.Context, in *CreateTaskRequest, opts ...grpc.CallOption) (*Task, error)
	GetTask(ctx context.Context, in *GetTaskRequest, opts ...grpc.CallOption) (*Task, error)
	ListTasks(ctx context.Context, in *ListTasksRequest, opts ...grpc.CallOption) (TaskService_ListTasksClient, error)
	RecordTasks(ctx context.Context, opts ...grpc.CallOption) (TaskService_RecordTasksClient, error)
	TaskChat(ctx context.Context, opts ...grpc.CallOption) (TaskService_TaskChatClient, error)
}

type taskServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTaskServiceClient(cc grpc.ClientConnInterface) TaskServiceClient {
	return &taskServiceClient{cc}
}

func (c *taskServiceClient) CreateTask(ctx context.Context, in *CreateTaskRequest, opts ...grpc.CallOption) (*Task, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Task)
	err := c.cc.Invoke(ctx, TaskService_CreateTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) GetTask(ctx context.Context, in *GetTaskRequest, opts ...grpc.CallOption) (*Task, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Task)
	err := c.cc.Invoke(ctx, TaskService_GetTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) ListTasks(ctx context.Context, in *ListTasksRequest, opts ...grpc.CallOption) (TaskService_ListTasksClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TaskService_ServiceDesc.Streams[0], TaskService_ListTasks_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &taskServiceListTasksClient{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TaskService_ListTasksClient interface {
	Recv() (*Task, error)
	grpc.ClientStream
}

type taskServiceListTasksClient struct {
	grpc.ClientStream
}

func (x *taskServiceListTasksClient) Recv() (*Task, error) {
	m := new(Task)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *taskServiceClient) RecordTasks(ctx context.Context, opts ...grpc.CallOption) (TaskService_RecordTasksClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TaskService_ServiceDesc.Streams[1], TaskService_RecordTasks_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &taskServiceRecordTasksClient{ClientStream: stream}
	return x, nil
}

type TaskService_RecordTasksClient interface {
	Send(*CreateTaskRequest) error
	CloseAndRecv() (*TaskSummary, error)
	grpc.ClientStream
}

type taskServiceRecordTasksClient struct {
	grpc.ClientStream
}

func (x *taskServiceRecordTasksClient) Send(m *CreateTaskRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *taskServiceRecordTasksClient) CloseAndRecv() (*TaskSummary, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(TaskSummary)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *taskServiceClient) TaskChat(ctx context.Context, opts ...grpc.CallOption) (TaskService_TaskChatClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TaskService_ServiceDesc.Streams[2], TaskService_TaskChat_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &taskServiceTaskChatClient{ClientStream: stream}
	return x, nil
}

type TaskService_TaskChatClient interface {
	Send(*TaskComment) error
	Recv() (*TaskComment, error)
	grpc.ClientStream
}

type taskServiceTaskChatClient struct {
	grpc.ClientStream
}

func (x *taskServiceTaskChatClient) Send(m *TaskComment) error {
	return x.ClientStream.SendMsg(m)
}

func (x *taskServiceTaskChatClient) Recv() (*TaskComment, error) {
	m := new(TaskComment)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TaskServiceServer is the server API for TaskService service.
// All implementations must embed UnimplementedTaskServiceServer
// for forward compatibility
type TaskServiceServer interface {
	CreateTask(context.Context, *CreateTaskRequest) (*Task, error)
	GetTask(context.Context, *GetTaskRequest) (*Task, error)
	ListTasks(*ListTasksRequest, TaskService_ListTasksServer) error
	RecordTasks(TaskService_RecordTasksServer) error
	TaskChat(TaskService_TaskChatServer) error
	mustEmbedUnimplementedTaskServiceServer()
}

// UnimplementedTaskServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTaskServiceServer struct {
}

func (UnimplementedTaskServiceServer) CreateTask(context.Context, *CreateTaskRequest) (*Task, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTask not implemented")
}
func (UnimplementedTaskServiceServer) GetTask(context.Context, *GetTaskRequest) (*Task, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTask not implemented")
}
func (UnimplementedTaskServiceServer) ListTasks(*ListTasksRequest, TaskService_ListTasksServer) error {
	return status.Errorf(codes.Unimplemented, "method ListTasks not implemented")
}
func (UnimplementedTaskServiceServer) RecordTasks(TaskService_RecordTasksServer) error {
	return status.Errorf(codes.Unimplemented, "method RecordTasks not implemented")
}
func (UnimplementedTaskServiceServer) TaskChat(TaskService_TaskChatServer) error {
	return status.Errorf(codes.Unimplemented, "method TaskChat not implemented")
}
func (UnimplementedTaskServiceServer) mustEmbedUnimplementedTaskServiceServer() {}

// UnsafeTaskServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TaskServiceServer will
// result in compilation errors.
type UnsafeTaskServiceServer interface {
	mustEmbedUnimplementedTaskServiceServer()
}

func RegisterTaskServiceServer(s grpc.ServiceRegistrar, srv TaskServiceServer) {
	s.RegisterService(&TaskService_ServiceDesc, srv)
}

func _TaskService_CreateTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).CreateTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_CreateTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).CreateTask(ctx, req.(*CreateTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_GetTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TaskServiceServer).GetTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TaskService_GetTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TaskServiceServer).GetTask(ctx, req.(*GetTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TaskService_ListTasks_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListTasksRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TaskServiceServer).ListTasks(m, &taskServiceListTasksServer{ServerStream: stream})
}

type TaskService_ListTasksServer interface {
	Send(*Task) error
	grpc.ServerStream
}

type taskServiceListTasksServer struct {
	grpc.ServerStream
}

func (x *taskServiceListTasksServer) Send(m *Task) error {
	return x.ServerStream.SendMsg(m)
}

func _TaskService_RecordTasks_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TaskServiceServer).RecordTasks(&taskServiceRecordTasksServer{ServerStream: stream})
}

type TaskService_RecordTasksServer interface {
	SendAndClose(*TaskSummary) error
	Recv() (*CreateTaskRequest, error)
	grpc.ServerStream
}

type taskServiceRecordTasksServer struct {
	grpc.ServerStream
}

func (x *taskServiceRecordTasksServer) SendAndClose(m *TaskSummary) error {
	return x.ServerStream.SendMsg(m)
}

func (x *taskServiceRecordTasksServer) Recv() (*CreateTaskRequest, error) {
	m := new(CreateTaskRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _TaskService_TaskChat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(TaskServiceServer).TaskChat(&taskServiceTaskChatServer{ServerStream: stream})
}

type TaskService_TaskChatServer interface {
	Send(*TaskComment) error
	Recv() (*TaskComment, error)
	grpc.ServerStream
}

type taskServiceTaskChatServer struct {
	grpc.ServerStream
}

func (x *taskServiceTaskChatServer) Send(m *TaskComment) error {
	return x.ServerStream.SendMsg(m)
}

func (x *taskServiceTaskChatServer) Recv() (*TaskComment, error) {
	m := new(TaskComment)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// TaskService_ServiceDesc is the grpc.ServiceDesc for TaskService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TaskService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tasks.TaskService",
	HandlerType: (*TaskServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTask",
			Handler:    _TaskService_CreateTask_Handler,
		},
		{
			MethodName: "GetTask",
			Handler:    _TaskService_GetTask_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListTasks",
			Handler:       _TaskService_ListTasks_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "RecordTasks",
			Handler:       _TaskService_RecordTasks_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "TaskChat",
			Handler:       _TaskService_TaskChat_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "tasks.proto",
}
